FROM node:20-alpine as build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
# We build specifying that the API will be proxied
ENV VITE_API_URL=/api
ENV VITE_WS_URL=/discovery
RUN npm run build

# Use Nginx to serve the built static UI
FROM nginx:alpine
COPY --from=build-stage /app/dist /usr/share/nginx/html
# Also configure Nginx internally or we can use the root nginx proxy
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
